name: Release Block Workflow

on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release Block
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.0

    - name: Install blocks cli
      run: npm install -g @airtable/blocks-cli

    - name: Configure blocks cli with api key
      env:
        BLOCKS_API_KEY: ${{ secrets.BlocksApiKey }}
      run: echo "$BLOCKS_API_KEY" | block set-api-key

    - name: Release block
      run: block release
